name: umat_srid_oapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  provider: ^6.1.5+1
  intl: ^0.19.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  # Alternative Firebase testing packages (optional - add only if you need testing)
  # fake_cloud_firestore: ^3.0.3
  # firebase_auth_mocks: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_launcher.png
    - assets/images/logo.jpg


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
